#pragma once
#include "util/unorgtypes.h"

struct filterSceneFog_s
{
	vec3_u dir;
	vec4_u colour;
	float nearPlane;
	float farPlane;
	unsigned __int8 additive;
	unsigned __int8 sky;
	float noiseAlphaStrength;
	float noiseAlphaRange;
	float noiseAlphaRamp;
	float noiseGrain;
	float noiseSpeed;
	vec3_u noiseDir;
};

struct filterScene_s
{
	vec3_u addScr;
	vec3_u addHsl;
	vec3_u addRgb;
	vec3_u mulRgb;
	vec4_u bloom;
	float bloomBleed;
	float monochrome;
	float monochromeProps;
	float motionBlur;
	float cameraBlur;
	float radialBlur;
	float zoomBlur;
	float noise;
	float edgeAmount;
	float embossAmount;
	float sharpenAmount;
	float dofAmount;
	float dofNear;
	float dofFar;
	float dofFocal;
	vec3_u rainDir;
	float rainSpeed;
	float rainDensity;
	float rainMapCoords[4];
	filterSceneFog_s fog[4];
	unsigned __int8 fogNum;
	unsigned __int8 atmosEnabled;
	float atmosRadius;
	float atmosHeight;
	float atmosDensity;
	float atmosAngleStartFade;
	float atmosAngleEndFade;
	float atmosMinFade;
	float fogMinHeight;
	float fogMaxHeight;
	float fogDensity;
	float fogAlpha;
	float heat;
	float heatScale;
	float heatSpeed;
	float heatNear;
	float heatFar;
};

struct sceneDescriptor_s
{
	char name[32];
	unsigned int handle;
	void* ioTemplate;
	float eastAngle;
	vec3_u east;
	vec3_u spaceEast;
	vec3_u ambCol;
	vec3_u spaceAmbCol;
	vec3_u spaceSunCol;
	float spaceSunIntensity;
	float spaceEastAngle;
	float spaceTimeOfDay;
	unsigned __int8 forceUpdate;
	vec3_u finalSunCol;
	float finalSunIntensity;
	float finalEastAngle;
	float finalTimeOfDay;
	vec3_u skyAmbCol;
	float skyAmbColScale;
	vec3_u skyCol;
	vec3_u sunCol;
	vec3_u occCol;
	vec3_u sunPos;
	vec3_u sunDir;
	vec3_u spaceSunPos;
	vec3_u spaceSunDir;
	unsigned __int8 sunLightEnabled;
	float sunIntensity;
	float occIntensity;
	float realTimeOfDay;
	float timeOfDay;
	float timeSunRise;
	float timeSunSet;
	vec3_u wiiSunsPos[4];
	vec3_u wiiSunsCol[4];
	float wiiSunSize[4];
	int wiiNumSuns;
	char wiiSunFile[256];
	float terrainLightScale;
	vec4_u terrainMaterialSpecularPower;
	vec4_u terrainMaterialIncandescense;
	int sunsNum;
	char sunsAssets[1024];
	unsigned int sunsTH[4];
	vec3_u sunsPos[4];
	float grassparting;
	float grassradius;
	float grassystrength;
	float grassshading;
	unsigned int cloudEnable;
	unsigned int cloudLayerEnable;
	char cloudLayerNoiseTex0Name[256];
	char cloudLayerNoiseTex1Name[256];
	float cloudLayerNoiseOctaveWeights[8];
	float cloudLayerNoiseOctaveEvolFreqs[8];
	float cloudLayerHalfHeight;
	float cloudLayerCover;
	float cloudLayerSharpness;
	float cloudLayerLightrayStepLength;
	float cloudLayerLightScattering;
	float cloudLayerMaxLighting;
	float cloudLayerMinLighting;
	vec3_u cloudLayerLightColor;
	vec3_u cloudLayerDarkColor;
	float cloudLayerNoiseTexTilingScale;
	float cloudLayerPlaneSizeScale;
	float cloudLayerPlaneAltitude;
	float cloudLayerCurvedPlaneRadius;
	float cloudLayerWindSpeed;
	float cloudLayerWindAngleFromXAxis;
	unsigned int cloudAreaEnable;
	float cloudAreaOctaveWeight[8];
	unsigned int cloudAreaNoIntersectingClouds;
	int cloudAreaCloudCount;
	vec3_u cloudAreaMax;
	vec3_u cloudAreaMin;
	vec3_u cloudAreaCloudSizeMin;
	vec3_u cloudAreaCloudSizeMax;
	float cloudAreaSharpness;
	float cloudAreaLightScattering;
	float cloudAreaMaxLighting;
	float cloudAreaMinLighting;
	vec3_u cloudAreaLightColor;
	vec3_u cloudAreaDarkColor;
	char cloudAreaNoiseTexName[256];
	float cloudAreaNoiseTexScaleTiling;
	float cloudAreaNoiseInfluence;
	int cloudVolumeFramebufferTexWidth;
	int cloudVolumeFramebufferTexHeight;
	int cloudVolumeFramebufferWidth;
	int cloudVolumeImpostorsTexSize;
	float cloudVolumeImpostorsLevelScaleThreshold[4];
	float cloudVolumeTransparencyZNear;
	float cloudVolumeTransparencyZFar;
	int cloudVolumeSliceCount;
	int cloudVolumeSliceTesselation;
	unsigned __int8 electricity_used;
	unsigned __int8 lightning;
	float flareRange;
	float flareScale;
	float flareMaxAlpha;
	float flareJitter;
	float flareNoise;
	unsigned __int8 flareOn;
	filterScene_s filters;
	vec3_u flareSunPos;
	vec3_u flareSunDir;
	float flareEastAngle;
	vec3_u flareEast;
	float flareRealTimeOfDay;
	float flareTimeOfDay;
	char rainMapName[256];
	char heatMapName[256];
	char envCubeMapName[256];
	char specCubeMapName[256];
	char skyCubeMapName[256];
	char skyCubeMapSunFlareName[256];
	char skyNonCubeMapName[256];
	char skyModelName[256];
	char atmosCubeMapName[256];
	char fogCubeMapName[256];
	char skyGroundDome[256];
	char skySpaceDome[256];
	char skyPlanet[256];
	unsigned int rainMap;
	unsigned int heatMap;
	unsigned int envCubeMap;
	unsigned int specCubeMap;
	unsigned int dappleMap;
	unsigned int atmosCubeMap;
	unsigned int fogCubeMap;
	__declspec(align(16)) mtx_u dappleMtx;
	unsigned __int8 hdrEnabled;
	float hdrLumAlpha;
	float hdrLumWhite;
	float hdrAdaptTimeScale;
	float hdrMaxAdaptedLum;
	float hdrMinAdaptedLum;
	float hdrBloomOffset;
	float hdrBloomThreshold;
	float hdrCompression;
	float hdrPowerLuminanceCalc;
	float hdrSampleRadius;
	vec3_u hdrBloomMotion;
	unsigned __int8 spaceLightEnabled;
	float spaceLightMax;
	float spaceLightMin;
	float farPlane;
	unsigned __int8 mistEnabled;
	vec4_u mistColour;
	float lightLOD;
	float CMLSunClamp;
	float CMLintensscale;
	float CMLScale[6];
	unsigned __int8 lightHackEnable;
	float reentryMinFx;
	float reentryMaxFx;
	float reentryTexStretch;
	float reentryBlendSpeed;
	float foliageSunVisibilityScale;
	float foliageSunVisibilityOffset;
	float shadowDistFadeStart;
	float shadowDistFadeEnd;
	float terrainDetailDistFadeStart;
	float terrainDetailDistFadeEnd;
	vec3_u weatherParticlesWind;
	vec3_u weatherParticlesPeriod;
	vec4_u weatherParticlesColour;
	float weatherParticlesSpeed;
	float weatherParticlesMaxDistance;
	float weatherParticlesHeight;
	float weatherParticlesDensity;
	float weatherParticlesZDensity;
	float weatherParticlesDropoff;
	float weatherParticlesLifetime;
	int weatherParticlesNumParticles;
	char weatherParticlesTexture[256];
};

struct  __declspec(align(16)) CPerViewSceneDescriptorSettings
{
	sceneDescriptor_s* m_sceneDescriptorNext;
	sceneDescriptor_s* m_sceneDescriptorCurrent;
	sceneDescriptor_s m_sceneDescriptorChanges;
	float m_sceneDescriptorBlendTime;
	float m_sceneDescriptorBlendLifetime;
	sceneDescriptor_s m_sceneDescriptor;
	unsigned int m_sunLight;
	bool m_used;
	bool m_set;
};

enum LightType : __int32
{
	LIGHT_TYPE_NULL = 0x0,
	LIGHT_TYPE_POINT = 0x1,
	LIGHT_TYPE_SPOT = 0x2,
};

struct LightSpotAttributes
{
	vec3_u dir;
	float angle;
	unsigned int texture;
};

struct LightBase
{
	union dimension
	{
		float radius;
	};
	unsigned int flags;
	unsigned __int16 findLightsID;
	unsigned __int8 exponent;
	unsigned __int8 pad;
	vec3_u pos;
	float colour[3];
	float invIntensity;
	unsigned int handle;
	BgRoom_s room;
	struct opaqueObInst* obInstH;
	unsigned int partNum;
	float intensity;
	unsigned int intensityExpOffset;
	LightType type;
	LightBase::dimension dimensions;
	float size;
	LightSpotAttributes spot;
	float cachedColour[3];
};

struct __declspec(align(4)) SceneVolumeData_s
{
	float hdrLumAlpha;
	float hdrLumWhite;
	float hdrMinAdaptedLum;
	float hdrMaxAdaptedLum;
	float hdrBloomOffset;
	float hdrBloomThreshold;
	float hdrCompression;
	float sunAngle;
	float spaceSunAngle;
	float sunTimeOfDay;
	float spaceSunTimeOfDay;
	float sunIntensity;
	float spaceSunIntensity;
	float finalSunIntensity;
	float sunRgb[3];
	float finalSunRgb[3];
	float spaceSunRgb[3];
	unsigned __int8 sunDraw;
	float flareRange;
	float flareSunTimeOfDay;
	float flareSunAngle;
	float flareScale;
	float flareMaxAlpha;
	float flareJitter;
	float flareNoise;
	unsigned __int8 flareDraw;
	unsigned int envCubeMap;
	unsigned int specCubeMap;
	unsigned int skyModelHandles[2];
	float skyModelWeights[2];
	char skyModelNum;
	float skyAmbientRgb[3];
	float skyAmbientBoost;
	float fogCol[3];
	float fogIntensity;
	float fogNear;
	float fogFar;
	unsigned __int8 fogSky;
	float dofIntensity;
	float dofNear;
	float dofFar;
	float rainIntensity;
	unsigned __int8 lightning;
	float noiseIntensity;
	float monoIntensity;
	float mulRgbCol[3];
	float addRgbCol[3];
	float addScrCol[3];
	float cmlSunClamp;
	float cmlSunScale;
	float cmlScale;
	float cmlScaleFace[6];
	unsigned __int8 cmlDetach;
};

struct SceneVolumeDataWeights_s
{
	float hdr;
	float sun;
	float flare;
	float sky;
	float fog;
	float dof;
	float mono;
	float rain;
	float noise;
	float mulRgb;
	float addRgb;
	float addScr;
	float cml;
};

extern int s_renderingUsingSceneDescriptorIndex;
extern CPerViewSceneDescriptorSettings s_sceneDescriptorArray[3];
extern LightBase worldlights[512];
extern SceneVolumeData_s s_volumeData[4];
void sceneDescriptorInitialise();
void skyInitialise();
void cloudInitialise();
void sceneVolumeDataValidate(int n);
void sceneDescriptorPrepareForRender(int i, viewdef_s* view);
void lightSetDirection(unsigned int light, const vec3_u* direction);