#pragma once

class CDictionary;

#include "Data/bf/settings_res.h"
#include "Data/common/constants/f_constants_res.h"
#include "Data/common/constants/constants_ai_res.h"
#include "Data/common/constants/constants_health_and_damage_res.h"
#include "Data/bf/constants/bf_constants_ai_res.h"
#include "Data/bf/constants/bf_constants_res.h"

struct __declspec(align(4)) rendererdebug_s
{
    float PCFScale;
    float shadowAtten;
    float shadowZOffset;
    float blobAngle;
    float blobRadius;
    float ati;
    float gunZRange;
    float brightness;
    float gamma;
    unsigned __int8 compressHDR;
    unsigned __int8 sortLayersFirst;
    unsigned __int8 seperateGunZRange;
    unsigned __int8 lightLineDraw;
    float grassParam1;
    float grassParam2;
    float grassParam3;
    float grassParam4;
    unsigned __int8 grassParam5;
    unsigned __int8 multisample;
    unsigned __int8 batchmode;
    unsigned __int8 texstream;
    unsigned __int8 texstreamhi;
    unsigned __int8 dbgmip;
    unsigned __int8 dbgDiffStreamedLevel;
    unsigned __int8 dbgLMapStreamedLevel;
    unsigned __int8 uselmap;
    unsigned __int8 usedif;
    unsigned __int8 usespec;
    unsigned __int8 usenrm;
    int minTexStreamLoadLevel;
    unsigned __int8 simpleHdr;
    unsigned __int8 shadowProjectWorkaround;
    float e3ShadowCullDist;
    int dbgMinMipPack;
    int dbgMaxMipPack;
    int dbgMipmapBase;
    float dbgMMChangeSpd;
    float lmapOfs;
    float lmapDist;
    float lmapsat;
    int dbgStreamRate;
    int dbgStreamDelay;
    unsigned __int8 drawmode;
    unsigned __int8 drawdecals;
    unsigned __int8 drawwater;
    unsigned __int8 prepassenabled;
    unsigned __int8 forceenvmap;
    unsigned __int8 wireframe;
    unsigned __int8 locklevels;
    unsigned __int8 killterrain;
    unsigned __int8 killgrass;
    int bindpose;
    float grassdrawdist;
    unsigned __int8 bpatch;
    unsigned __int8 stitchonly;
    unsigned __int8 drawshadows;
    unsigned __int8 forceShadowsOff;
    unsigned __int8 drawbackshadows;
    unsigned __int8 enablelights;
    unsigned __int8 enablerimlight;
    float rimlightWidth;
    float rimlightFade;
    float rimlightValue;
    unsigned __int8 drawlights;
    unsigned __int8 drawbglights;
    float lightLOD;
    float lightHackScale;
    float lightHackDistance;
    float lightHackVertOffset;
    unsigned __int8 lightStats;
    unsigned __int8 drawportals;
    unsigned __int8 drawwrcliprect;
    unsigned __int8 drawocc;
    unsigned __int8 drawBBText;
    unsigned __int8 drawroombbs;
    unsigned __int8 drawfloors;
    unsigned __int8 drawfloorhits;
    unsigned __int8 drawbbs;
    unsigned __int8 drawellips;
    int ellipsDetail;
    unsigned __int8 drawspheres;
    int sphereDetail;
    int drawPart;
    unsigned __int8 drawbgbs;
    unsigned __int8 drawrbs;
    int drawsky;
    unsigned __int8 drawclouds;
    unsigned __int8 drawforces;
    unsigned __int8 drawnavmesh;
    unsigned __int8 drawterrain;
    unsigned __int8 showTerrainLevels;
    float terrainLightmapScale;
    unsigned __int8 updateTerrain;
    unsigned __int8 updateTerrainEarlyUpdate;
    unsigned __int8 updateTerrainMultithreaded;
    unsigned __int8 updateTerrainAsynchronously;
    unsigned __int8 useTerrainStreamedMegatex;
    unsigned __int8 useterraincallback;
    unsigned __int8 terrainDebugShadow;
    unsigned __int8 backgroundCastOntoTerrain;
    unsigned __int8 terrainShadowExpensiveFilter;
    unsigned __int8 terrainUseLightmapNear;
    unsigned __int8 terrainUseLightmapFilter;
    float terrainDiffuseAmbient;
    float terrainSunWeight;
    unsigned __int8 updateMegatex;
    unsigned __int8 usefloors;
    unsigned __int8 alphaasopa;
    unsigned __int8 particleDraw;
    unsigned __int8 particleDrawCML;
    unsigned __int8 particleDrawBounds;
    unsigned __int8 particleDrawGeoms;
    unsigned __int8 particleDrawInfo;
    unsigned __int8 particleDrawOverdrawShader;
    unsigned __int8 particleDrawSimpleShader;
    unsigned __int8 particleDrawSprites;
    unsigned __int8 particleTickCollisions;
    unsigned __int8 particleSorting;
    unsigned __int8 particleResolution;
    unsigned __int8 particleDrawSystemNames;
    unsigned __int8 drawweathers;
    unsigned __int8 drawproptree;
    unsigned __int8 drawcollisionmesh_readFromDbgMgr;
    unsigned __int8 drawcollisionmesh;
    unsigned __int8 drawlinetestmesh;
    unsigned __int8 drawcollisionmesh_colsFromNormal;
    unsigned __int8 drawcollisionmesh_filled;
    unsigned __int8 drawcollisionmeshbounds;
    unsigned __int8 drawcollisionmesh_player_shoot_through;
    unsigned __int8 drawcollisionmesh_ai_shoot_through;
    unsigned __int8 drawcollisionmesh_ai_see_through;
    unsigned __int8 shadowGroup;
    unsigned __int8 shadowculling;
    unsigned __int8 terrainShadowProject;
    unsigned __int8 fastproject;
    unsigned __int8 separatebgsb;
    unsigned __int8 usefrontfaces;
    unsigned __int8 viewshadowbuffer;
    unsigned __int8 debugBackgroundShadows;
    unsigned __int8 combineambientlit;
    unsigned __int8 omptest;
    unsigned __int8 ignoredAssertPrintfs;
    unsigned __int8 printfs;
    int navDrawDist;
    unsigned __int8 drawnormals;
    unsigned __int8 drawldlc;
    unsigned __int8 profileDisplay;
    unsigned __int8 soundTest;
    unsigned __int8 soundProfile;
    int profileDumpText2Delayed;
    unsigned __int8 profileDumpText;
    unsigned __int8 profileResetSpikes;
    unsigned __int8 profileDumpPcap;
    unsigned __int8 statsDisplay;
    unsigned __int8 statsObDisplay;
    unsigned __int8 statsTexDisplay;
    unsigned __int8 statsRoomDisplay;
    unsigned __int8 fasterShadowCast;
    unsigned __int8 useSphericalH;
    unsigned __int8 useSphericalHBG;
    unsigned __int8 showJoypadInputs;
    float shadowBufOffsetScale;
    float shadowBufOffsetTranslate;
    float texelsPerMeter;
    float shadowCloseDistClamp;
    float maxInGameTexRes;
    float shadowDarkness;
    unsigned __int8 dynamicSunlight;
    unsigned __int8 spotlightCull;
    unsigned __int8 shadowDebugDraw;
    unsigned __int8 overdrawDebugGfx;
    unsigned __int8 shadowMinimiseArea;
    unsigned __int8 debugTex;
    int debugTexIdx;
    unsigned __int8 debugCubeMapLighting;
    unsigned __int8 debugCubeMapLightingVols;
    unsigned __int8 debugShNonePlayerProps;
    unsigned __int8 displaySkinLMap;
    float lightingWrapValue;
    float blurSkinLMapFactor;
    unsigned __int8 skinbfculltest;
    unsigned __int8 sortPasses;
    unsigned __int8 enablePropDrawing;
    unsigned __int8 enableBgDrawing;
    unsigned __int8 renderBatchCulling;
    unsigned __int8 frustumCullBgSurfaces;
    unsigned __int8 homTestPoly2DEnabled;
    unsigned __int8 bginstAABBFrustumClipping;
    unsigned __int8 roomAABBWorldRoomFrustumClipping;
    unsigned __int8 bgUsePortalsForVisRooms;
    unsigned __int8 useOBBFrustumClip;
    unsigned __int8 usePropContribCulling;
    float propContribCullSize;
    unsigned __int8 propOcclusionGFXEnabled;
    unsigned __int8 propDistCullingEnabled;
    float propCullDist;
    unsigned __int8 drawElements;
    unsigned __int8 noenginetick;
    unsigned __int8 shadercache;
    unsigned __int8 skinvbo;
    unsigned __int8 varyingcache;
    unsigned __int8 uniformcache;
    unsigned __int8 volfogEnable;
    unsigned __int8 volfogEnableDebug;
    int volfogBlurPasses;
    unsigned __int8 envMapEnable;
    unsigned __int8 dynamicEnvMapEnable;
    unsigned __int8 envMapDebugGFX;
    unsigned __int8 envMapPriority;
    int envMapCamFOV;
    unsigned __int8 envMapLighting;
    float envMapIncan;
    float envMapScale;
    float envMapMinClamp;
    unsigned __int8 incanSetting;
    float lightBlendTime;
    float CMLSunClamp;
    unsigned __int8 displayBadCML;
    unsigned __int8 detachCML;
    float CMLVerticalHack;
    unsigned __int8 frameratelock;
    unsigned __int8 frameratelockEnabled;
    unsigned __int8 cpuSkinOptimisations;
    unsigned __int8 enableSkinning;
    unsigned __int8 enableDetailGeom;
    unsigned __int8 filterGfxDisable;
    unsigned __int8 fadePortalsEnabled;
    unsigned __int8 disableFaceMeGfx;
    unsigned __int8 disableGrassGfx;
    unsigned __int8 grassGfxBefore;
    unsigned __int8 disableFoliageGfx;
    unsigned __int8 disableAlphaCutout;
    unsigned __int8 disablePortalCullingOnProps;
    unsigned __int8 shaderJitCompile;
    unsigned __int8 shaderDisableNormMap;
    unsigned __int8 shaderDisableSpecMap;
    unsigned __int8 shaderDisableLMap;
    unsigned __int8 enableHotFileReloading;
    unsigned __int8 particlereload;
    unsigned __int8 drawPropsBeforeBg;
    unsigned __int8 sdHideChanges;
    unsigned __int8 shaderUseSpecMap;
    unsigned __int8 shaderUseNdotL;
    unsigned __int8 editSceneDescriptors;
    unsigned __int8 disableSceneVolumes;
    unsigned __int8 disableFltrAtmosphere;
    unsigned __int8 disableFltrAngleFade;
    unsigned __int8 disableFltrBase;
    unsigned __int8 disableFltrHsl;
    unsigned __int8 disableFltrFog;
    unsigned __int8 disableFltrRain;
    unsigned __int8 disableFltrDof;
    unsigned __int8 disableFltrHeat;
    unsigned __int8 disableFltrBloom;
    unsigned __int8 disableFltrBlur;
    unsigned __int8 disableFltrBlurCamera;
    unsigned __int8 disableFltrBlurRadial;
    unsigned __int8 disableFltrBlurZoom;
    unsigned __int8 disableFltrFocus;
    unsigned __int8 disableFltrEdge;
    unsigned __int8 disableFltrEmboss;
    unsigned __int8 disableFltrSharpen;
    unsigned __int8 disableFltrSphere;
    unsigned __int8 disableFltrDigitalZoom;
    unsigned __int8 disableFltrDoubleVision;
    unsigned __int8 disableFltrMalfunction;
    unsigned __int8 disableFltrScreenShake;
    unsigned __int8 disableFltrOptimal;
    unsigned __int8 disableFltrPerception;
    unsigned __int8 disableFltrAddRgb;
    unsigned __int8 disableFltrAddScr;
    unsigned __int8 disableFltrMulRgb;
    unsigned __int8 disableFltrMonochrome;
    unsigned __int8 disableFltrMotion;
    unsigned __int8 disableFltrNoise;
    unsigned __int8 disableFltrHealth;
    unsigned __int8 linkFlarePosWithSun;
    unsigned __int8 disableSunDecal;
    unsigned __int8 disableSpacePosUpdate;
    unsigned __int8 lodObEnable;
    unsigned __int8 lodObShadowsEnable;
    unsigned __int8 lodObOverrideEnable;
    int lodObShadowReduction;
    int lodObReduction;
    int lodObOverrideLevel;
    int lodObOverrideDist;
    unsigned __int8 lodPartEnable;
    unsigned __int8 lodPartOverrideEnable;
    int lodPartOverrideLevel;
    unsigned __int8 lodPartEllipsoidDist;
    unsigned __int8 lodPartMergeEnable;
    float lodMergeClipdist;
    unsigned __int8 lodBlendEnable;
    int lodBlendSpeed;
    unsigned __int8 detailPartsCullingEnable;
    unsigned __int8 detailPartsCullingOverrideEnable;
    float detailPartsCullingOverrideDist;
    unsigned __int8 detailPartsCullingOverrideAlwaysCull;
    unsigned __int8 enableTextures;
    unsigned __int8 enableHighDef;
    float overrideSkyFOV;
    float scaleOptimalFilter;
    int perceptionTest;
    int screenshot_width;
    int screenshot_height;
    unsigned int screenshot_count;
    unsigned __int8 screenshot_first;
    unsigned __int8 perf;
    unsigned __int8 perfhdrdisable;
    unsigned __int8 forceQuit;
    float bodge;
    unsigned __int8 memPrintAll;
    char* loadingMessage;
    float testScaleTerrain;
    float foliageWindDirection;
    float dkshieldBias;
    float dkshieldScale;
    float dkshieldPower;
    float dkshieldFeedbackStrength;
    unsigned __int8 enableAlternativeTerrain;
    int terrainHeightfieldLevel;
    int foliageDebugType;
    float foliageDrawDistMin;
    float foliageDrawDistMax;
    float foliageDrawDistFadeLen;
    unsigned __int8 foliageDisplayStats;
    float foliageDensityScale;
    float heightfieldTau;
    float heightfieldNearVal;
    float heightfieldTopVal;
    unsigned __int8 heightfieldBorderBlend;
    float healthEffectDuration;
    float healthEffectIntensity;
    unsigned __int8 terrainDebugSlopes;
};
struct MemInitData
{
    unsigned __int8* heap;
    int heapSize;
    int dictContentsHeapSize;
    int hashDictHeapNumber;
    int packedDictionaryNumber;
    int fixedSizeDictHeapSize;
    int fixedSizeDictHeapNumber;
    int fixedSizeArrayHeapSize;
    int fixedSizeArrayHeapNumber;
};

enum ViewerType : __int32
{
    VIEWER_INGAME = 0x0,
    VIEWER_QUICKVIEWER = 0x1,
    VIEWER_EDITOR = 0x2,
};

struct __declspec(align(2)) EngineInitData
{
    MemInitData memInitData;
    int DebugDrawBufferSize;
    int FontBufferSize;
    float shadowQuality;
    unsigned __int16 screenResX;
    unsigned __int16 screenResY;
    unsigned __int16 fullScreenResX;
    unsigned __int16 fullScreenResY;
    unsigned __int16 windowedResX;
    unsigned __int16 windowedResY;
    float pixelAspect;
    float screenAspect;
    ViewerType Viewer;
    unsigned int FullScreen;
    unsigned int DisablePathExpansion;
    unsigned int EngineDebugKeys;
    unsigned int lockFramerateTo;
    unsigned int buildNumber;
    unsigned __int8 soundEnable;
    unsigned __int8 shadowEnable;
    unsigned __int8 graphicsEnable;
    unsigned __int8 inputEnable;
    unsigned __int8 displayAspect4x3;
    unsigned __int8 pal;
    unsigned __int8 displayIsSD;
};

struct WorldState_e { enum { UNINITIALISED = 0, INITIALISED = 1, RUNNING = 2, DEINITIALISING = 3 }; };

int engineHandleArguments(int argc, char** argv);
void rendererDebugInitialise();

extern rendererdebug_s rdebugflags;
extern unsigned __int8 g_enableHotReload;
extern unsigned __int8 s_soundEnable;
extern unsigned __int8 s_soundJIT;
extern float s_shadowQuality;
extern unsigned __int8 sForceLDR;
extern unsigned __int8 sHdrEnabledNext;
extern unsigned __int8 s_hdrFirstFrame[4];
extern unsigned __int8 g_disableMipmaps;
extern char* g_unitName;
extern unsigned __int8 cacheSyncEnabled;
extern unsigned __int8 cacheEnabled;
extern float maxPostAttackAngleDot;
extern float c_PhantomMovementExpansionRatio;
extern float radius;
extern float maxLimit;
extern float s_depthCutoffDist;
extern float s_mpRate;
extern EngineInitData initData;
extern unsigned int  timerRenderFrameNum;
extern const char* s_hwPath;
extern settings_res* g_settings;
extern f_constants_res* g_constants;
extern constants_ai_res* g_constants_ai;
extern constants_health_and_damage_res* g_constants_healt_hand_damage;
extern bf_constants_ai_res* g_bf_constants_ai;
extern bf_constants_res* g_bf_constants;
extern unsigned int timerGameFrameNum;
extern double timerGameTime;
extern double timerTargetGameTime;
extern float timerLastFrameDuration;
extern float timerLastGameFrameDuration;
extern double timerFrameStartTime;